var appMessages = {

    serverError: "Something went wrong!!!",
    success: "success",
    error: "error",

    appErrorMessages: {
        failedLogin: "Sorry, Email or password not found.",
        failedAuthorization: "Sorry, you are not authorized.",
        unique: "Email already exists, please try with different email.",
        notPermit: "You  have not permission to perform this function.",
        ActionfailedAuthorization: "Sorry, you are not authorized. Please provide action .",
        expireToken: "Your token has expired.",
        notAuthoritytoCreateUser: "You are not authorized to create user of this access.",
        badRequest: "Invalid request data.",
        invalidEmail: "email is not valid",
        invalidUserNamePassword: "Invalid userName or Password",
        oldPassword: "Old password did not match",
        notPassword: "Please enter password",
        emailFailed: "Error occurred while sending mail",
        userNotFound: "User not found",
        phoneNumberExit: "This phone number is already registered",
        notRegister: "Mobile number is not registered.",
        authTokenError: "Error generating authentication token",
        alreadyRegistered: "Username or email already exists",
        emailNOtFound: "User email not found",
        queryError: "Database queryError",
    },
    userMessages: {
        registrationSuccess: "Registration successful",
        userNotFound: "User not found",
        invalidUser: "Invalid User",
        invalidKeyFile: "This is not valid key file",
        profileUpdateError: "Unable to update profile",
    },
    mailMessages: {
        resetMailSent: "Reset Password email sent",
        supportMail: "Mail successfully send to support team"
    },

    packageMessages: {
        notFound: "No Package Found"
    },

    verifyUserTemplateMesg: {
        verifyUsername: "Verify Username", // txnChange
        verifyMsg: "enter this security code: ", // yourTxnPsw
        wrongSecurityCode: "Wrong Security code or login again"
    },
    passphraseTemplateMesg: {
        passphraseMsg: "Your Wallet Passphrase is: ",
        passphraseSubject: "Wallet Passphrase",
        nothaveWallet: " has not created wallet, Unable to find user passphrase",
        successMessage: "Passphrase sent to registered email"
    },
    autoGeneratedMessages: {
        convertedFromTokens: "Converted from Tokens",
        accountToWallet: "Transfer from Account to Daxx-wallet"
    },

    mailManagementMessages: {
        mailAddedSuccess: "Mail sent successfully",
        mailAddedError: "Mail cannot be sent",
        mailDeleteSuccess: "Mail deleted successfully",
        mailDeleteError: "Unable to delete mail"
    },
}


module.exports.appMessages = appMessages
